[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && /opt/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[build.envs]
PYTHON_VERSION = "3.11"

# Force Railway to use backend context
[build.context]
path = "backend"

[deploy.context]
path = "backend"

# Override the install command to use backend requirements
[build.install]
cmd = "pip install -r requirements.txt"
cmd = "pip install -r /backend/requirements.txt"